### ISSUE TITLE
Include all Kanto components in the project's release configuration

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/kanto#122]
Update the available `.goreleaser.yaml` configuration to include the newly introduced Kanto building blocks targeted for the upcoming M2 release:
* Local Digital Twins
* Suite Bootstrapping
* File Backup
* System Metrics

The configuration must ensure the needed builds and packaging of these components in available packaging formats.

**Comment by daniel-milchev** [comment]
I'll have a look at this.

**Comment by e-grigorov** [comment]
Currently, the Kanto debian package cannot start the suite bootstrapping service because there is no dynamic monitoring of the provisioning file. The related ticket is: eclipse-kanto/suite-bootstrapping#17. The system administrator has to do so once the bootstrapping subscription is provided to the device. This behavior will be revised when the linked ticket is implemented.

**Comment by dimiter-todorov-georgiev** [comment]
There is an issue when both the local digital twin, and the suite-connector, cannot be enabled as services at the same time. Please don't start local digital twin by default.
