### ISSUE TITLE
Fix quickstart code resources for working with Eclipse Hono Sandbox

### ISSUE THREAD

**Issue by gabriela-yoncheva** [eclipse-kanto/kanto#16]
After following the Explore via Eclipse Hono guide, when executing the quick-start code resources, they didn't work as explained in the guide:
- [hono_events.py](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_events.py) is not connecting and as a result not receiving any events from Eclipse Hono Sandbox
- [hono_commands.py](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands.py)  is not connecting or sending commands to Eclipse Hono Sandbox and as a result a container is not created

Acceptance:
- The quick-start code resources must work in accordance to the Explore via Eclipse Hono guide

If needed, contact Eclipse Hono support.

**Comment by sophokles73** [comment]
@gabriela-yoncheva do you have any client side logs that could indicate what is happening and what might have gone wrong?

**Comment by ognian-baruh** [comment]
Hello, @sophokles73 

Together with @gabriela-yoncheva, we have been investigating the issue in attempts to find the possible source of the problem.

We are currently trying to run the a command invoker which sends messages to the AMQP endpoint of the Eclipse Hono Sandbox using the [Qpid Proton Python API](https://qpid.apache.org/releases/qpid-proton-0.31.0/proton/python/docs/index.html). The code we are executing is located [here](https://github.com/eclipse-kanto/kanto/blob/399d1c9b1f3fa686b6e55fb1898655481b6eab7a/quickstart/hono_commands.py#L62). We overrode the callback functions of the [Proton MessagingHandler](https://qpid.apache.org/releases/qpid-proton-0.31.0/proton/python/docs/proton.handlers.html#proton.handlers.MessagingHandler) in order to generate some logs.

Here are the logs, generated when executing the code: [logs.log](https://github.com/eclipse-kanto/kanto/files/8940581/logs.log)

From what I can understand, a connection is being established (visible from lines 4-85 in the log file). When a sender is created, it seems like the Proton Container object is waiting for events/messages (visible from lines 87-110 in the log file, and repeating from then on), but it never invokes the `on_sendable` callback function and a message is never sent via the Sandbox.

We are provisioning the device using the [hono_provisioning.sh](https://github.com/eclipse-kanto/kanto/blob/399d1c9b1f3fa686b6e55fb1898655481b6eab7a/quickstart/hono_provisioning.sh) script with the following configurations:

```sh
# The Hono AMQP endpoint to connect to
export HONO_EP=hono.eclipseprojects.io
# The Hono tenant to be created
export TENANT=tenant20061257
# The identifier of the device on the tenant
# Note! It's important for the ID to follow the convention namespace:name (e.g. edge:device)
export DEVICE_ID=tenant20061257:device1
# The authentication identifier of the device
export AUTH_ID=tenant20061257_device1
# A password for the device to authenticate with
export PWD=admin
```

The device is successfully provisioned in the Eclipse Hono Sandbox and we verified it by using the Device Management Registry REST API.

On a side note, we tried subscribing for commands for this device, using Mosquitto:
`mosquitto_sub -v -t 'command///req/#' -h hono.eclipseprojects.io -p 1883 -u tenant20061257_device1 -P admin`
When executing this command in the CLI, the result we get is:
`Connection error: Connection Refused: bad user name or password.`

It may not be relevant as this issue would have impact when the command reaches the device and it gets lost prior to even being sent to it but I decided to mention it in case it is helpful to you.

Thank you for taking your time, we will stay in touch if any more information is required.

**Comment by sophokles73** [comment]
On first impression, I do not see anything wrong with your Python script. However, I am not a Python expert so I might as well be mistaken ...

**Comment by sophokles73** [comment]
However, I have tested to subscribe to commands for the given device and were able to send a one-way command to it using the Hono command line client via the Hono Sandbox.

**Comment by sophokles73** [comment]
@ognian-baruh  Have you tried to send the command _after_ you have successfully subscribed to commands?

**Comment by konstantina-gramatova** [comment]
Hey @sophokles73 - thanks for jumping in!

What I can share from different experiments we tried out, is the following summary:

* when a new tenant is created, a new device is provisioned for this tenant but the device has never initiated a subscription to the MQTT Hono commands topic - the Python AMQP invoker handler is never called back
* when a new tenant is created, a device is provisioned for this tenant and the device has made at least one successful subscription to the MQTT Hono commands topic prior to sending the command via AMQP - the Python AMQP invoker handler is called back
* when using an existing tenant that has at least one device that has ever initiated a successful MQTT Hono commands subscription, provisioning another new device for this tenant that has never initiated any kind of MQTT subscriptions to Hono - the Python AMQP invoker handler for this new device is called back

Looks like the Python AMQP invoker handler never gets called back when there is a tenant with devices that have never initiated a successful subscription to Hono.

In all of the use cases described above - no errors were caught by any of the provided by the AMQP library API error handlers/input parameters.


Given this observation - any ideas? Is this an expected Hono behavior or a known issue?

**Comment by sophokles73** [comment]
This is indeed the expected behavior. The AMQP 1.0 based messaging network will only start issuing *credits* to your application side sender link, once a device belonging to the same tenant has connected to a protocol adapter and registered for receiving commands. That is because this connection by the device is used as the trigger to establish the (tenant scoped) receiver link with the AMQP 1.0 messaging network and that, in turn, is the trigger for the Dispatch Router to (initially) issue credits to your sender.

For an exiting tenant for which one of its devices has already connected, all that has already happened and that is why your sender in that case gets credits immediately.

**Comment by konstantina-gramatova** [comment]
@sophokles73 Given all the described above prerequisites regarding connectivity are fulfilled:
* there is a tenant successfully created
* there's a successfully provisioned and connected device for this tenant
* there's a successfully running AMQP `event/<tenant>`  consumer on the northbound side

Currently, using the Hono sandbox, the AMQP consumer does not receive any events from the device being published on the MQTT southbound side (tested with MQTT Explorer manually, topic `event`, QoS 1). Are we missing something in the setup/sequence or the sandbox may be unstable for some reason?

**Comment by sophokles73** [comment]
I suspect your tenant to be configured to use Kafka based messaging, which is the default messaging infrastructure with Hono 2.0.0. The Sandbox still supports using both Kafka and/or AMQP 1.0. However, if you want to use AMQP 1.0 messaging infra with your tenant, then you need to explicitly set the *ext/messaging-type* property to `amqp` in your tenant's configuration. See https://www.eclipse.org/hono/docs/admin-guide/amqp-network-config/#configuring-tenants-to-use-amqp-10-based-messaging

**Comment by konstantina-gramatova** [comment]
Thanks for the hint! We'll ensure an AMQP connectivity is configured for the tenants used in all Python scripts.

It's funny though, that the AMQP consumers were actually partially working even without an explicit configuration on the tenant being set with the current Hono sandbox - the AMQP message handlers kept sending and receiving  on `command/<tenant>` and on (a little bit shaky) `command_response/<tenant>/replies` - only the consuming events was not working at all...)

**Comment by sophokles73** [comment]
That is actually expected behavior. We also support the simultaneous usage of Kafka *and* AMQP 1.0 based messaging for a tenant. In such cases, commands sent via AMQP 1.0 still reach the devices and responses are sent back via the messaging infra that had been used for sending the command(s). Such a setup can be used for zero-downtime migration from AMQP to Kafka based messaging ...

**Comment by konstantina-gramatova** [comment]
@sophokles73 Thank you for the info & clarifications! We'll keep that in mind for future setups & scenarios :blush:

**Comment by ognian-baruh** [comment]
After some help from the Eclipse Hono support team, we have resolved the issues we had regarding the Python scripts for the How-to guides and specifically the connection, subscription and communication with the Eclipse Hono sandbox. Hence, this issue will be closed and if any other issues emerges, a separate issue will be opened.
