### ISSUE TITLE
More Info related to provisioning.json,  suite-connector-config & suite-bootstrapping-config

### ISSUE THREAD

**Issue by xm1k3** [eclipse-kanto/kanto#291]
Hi, 
I would like to ask you if it is possible to have more information about [suite-bootstrapping-config](https://eclipse.dev/kanto/docs/references/connectivity/suite-bootstrapping-config/#template) and [suite-connector-config](https://eclipse.dev/kanto/docs/references/connectivity/suite-connector-config/#template) in the documentation you have written as json template, in particular I would like to understand how to connect Kanto to another tool other than Bosch IoT Device.
also, is the provisioning.json generated by Bosch IoT Device or is there an example somewhere I can see?

Thank you

**Comment by dimitar-dimitrow** [comment]
Hi @xm1k3 ,

when connecting to other tools/clouds it is not recommended to use a `provisioning.json` as it is specific to Bosch IoT Suite and generated by it. To connect to other tools/clouds MQTT endpoints, it is recommended to set up the [Remote connectivity settings](https://eclipse.dev/kanto/docs/references/connectivity/suite-connector-config/#properties) of the the `suite-connector`. Here are some guidelines and examples:
- Check the [Explore via Eclipse Hono](https://eclipse.dev/kanto/docs/getting-started/hono/) where Kanto is connected to a publicly available Eclipse Hono Sandbox.
- An example how to connect to an AWS IoT Core MQTT Endpoint using the suite-connector
```suite-connector -address=<aws-mqtt-endpoint> -caCert=<path>/aws.crt -cert=<path>/device.cert -key=<path>/device.key -clientId=<mqtt-client-unique-id> -deviceId=<device-unique-identifier> -tenantId=<tenant-unique-identifier>```
- [AWS](https://github.com/eclipse-kanto/aws-connector) and [Azure](https://github.com/eclipse-kanto/azure-connector) specific connectors that can be used instead of the suite-connector.

The `suite-bootstrapping` could be used to initially connect devices, that are shipped with a uniform setup, to a single bootstrapping subscription, send a bootstrapping request and receive a bootstrapping response that contains the needed information to connect to the real target subscription. The `suite-bootstrapping` in the same way as the `suite-connector` could also be initially connect via the [Remote connectivity settings](https://eclipse.dev/kanto/docs/references/connectivity/suite-bootstrapping-config/). The `suite-bootstrapping` also allows custom JSON data to be received as a bootstrapping response and then be consumed by the `postBootstrapScript` file in order to correctly configure the suite-connector to connect to the real target subscription.

If you provide information to which tool/cloud you are trying to connect or have any other questions, please feel free to continue the discussion.

**Comment by dimitar-dimitrow** [comment]
@xm1k3, did you managed to configure the connection to the tool/cloud? Soon I will close the issue, as it becomes stale. If any additional information is needed, do not hesitate to re-open or open a new issue.
